services:
  app:
    image: "epicmorg/bitbucket:8.19.8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:8.19.8
  app-jdk17:
    image: "epicmorg/bitbucket:8.19.8-jdk17"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:8.19.8-jdk17
