services:
  app:
    image: "epicmorg/bitbucket:5.16.9"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:5.16.9
      - docker.io/epicmorg/bitbucket:5.16.9-jdk8
      - quay.io/epicmorg/bitbucket:5.16.9
      - quay.io/epicmorg/bitbucket:5.16.9-jdk8
      - ghcr.io/epicmorg/bitbucket:5.16.9
      - ghcr.io/epicmorg/bitbucket:5.16.9-jdk8
