services:
  app:
    image: "epicmorg/nginx:1.30-php5.6"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/nginx:1.30-php5.6
      - ghcr.io/epicmorg/nginx:1.30-php5.6
      - docker.io/epicmorg/nginx:1.30-php5.6
