services:
  app:
    image: "epicmorg/crowd:4.4.4"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:4.4.4
  app-jdk8:
    image: "epicmorg/crowd:4.4.4-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:4.4.4-jdk8
  app-jdk11:
    image: "epicmorg/crowd:4.4.4-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - quay.io/epicmorg/crowd:4.4.4-jdk11
