services:
  app:
    image: "epicmorg/jira:4.4.5"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:4.4.5
  app-jdk6:
    image: "epicmorg/jira:4.4.5-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:4.4.5-jdk6
