services:
  app:
    image: "epicmorg/python:3.6"
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/python:3.6
      - quay.io/epicmorg/python:3.6
      - ghcr.io/epicmorg/python:3.6
    build:
      context: .
