services:
  app:
    image: "epicmorg/mongo:1.6"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/mongo:1.6
      - ghcr.io/epicmorg/mongo:1.6
      - docker.io/epicmorg/mongo:1.6
      - quay.io/epicmorg/mongo:1.6.5
      - ghcr.io/epicmorg/mongo:1.6.5
      - docker.io/epicmorg/mongo:1.6.5
