FROM epicmorg/devel
LABEL maintainer="EpicMorg DevTeam, developer@epicm.org"
ARG DEBIAN_FRONTEND=noninteractive

ADD pre/ngninx.pre.tar.gz /



#FROM epicmorg/prod
#LABEL maintainer="EpicMorg DevTeam, developer@epicm.org"
#ARG DEBIAN_FRONTEND=noninteractive

#final config
#VOLUME ["/var/cache/nginx"]
#EXPOSE 80 443

#CMD ["nginx", "-g", "daemon off;"]
