services:
  app:
    image: "epicmorg/confluence:"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:
      - docker.io/epicmorg/confluence:-jdk8
      - quay.io/epicmorg/confluence:
      - quay.io/epicmorg/confluence:-jdk8
      - ghcr.io/epicmorg/confluence:
      - ghcr.io/epicmorg/confluence:-jdk8
