services:
  app:
    image: "epicmorg/jira:8.14.0"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/jira:8.14.0
      - quay.io/epicmorg/jira:8.14.0
      - ghcr.io/epicmorg/jira:8.14.0
  app-jdk8:
    image: "epicmorg/jira:8.14.0-jdk8"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/jira:8.14.0-jdk8
      - quay.io/epicmorg/jira:8.14.0-jdk8
      - ghcr.io/epicmorg/jira:8.14.0-jdk8
  app-jdk11:
    image: "epicmorg/jira:8.14.0-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - docker.io/epicmorg/jira:8.14.0-jdk11
      - quay.io/epicmorg/jira:8.14.0-jdk11
      - ghcr.io/epicmorg/jira:8.14.0-jdk11
