services:
  app:
    image: "epicmorg/bitbucket:5.16.8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:5.16.8
  app-jdk8:
    image: "epicmorg/bitbucket:5.16.8-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:5.16.8-jdk8