services:
  app:
    image: "epicmorg/astralinux:1.8-rootfs"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/astralinux:1.8-rootfs
      - ghcr.io/epicmorg/astralinux:1.8-rootfs
