services:
  app:
    image: "epicmorg/bitbucket:5.0.8"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:5.0.8
      - docker.io/epicmorg/bitbucket:5.0.8-jdk8
      - quay.io/epicmorg/bitbucket:5.0.8
      - quay.io/epicmorg/bitbucket:5.0.8-jdk8
      - ghcr.io/epicmorg/bitbucket:5.0.8
      - ghcr.io/epicmorg/bitbucket:5.0.8-jdk8
