services:
  app:
    image: "epicmorg/bitbucket:2.9.3"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:2.9.3
  app-jdk7:
    image: "epicmorg/bitbucket:2.9.3-jdk7"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:2.9.3-jdk7
