services:
  app:
    image: "epicmorg/bitbucket:3.2.7"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:3.2.7
      - docker.io/epicmorg/bitbucket:3.2.7-jdk8
      - quay.io/epicmorg/bitbucket:3.2.7
      - quay.io/epicmorg/bitbucket:3.2.7-jdk8
      - ghcr.io/epicmorg/bitbucket:3.2.7
      - ghcr.io/epicmorg/bitbucket:3.2.7-jdk8
