services:
  app:
    image: "epicmorg/testrail:5.0.0.3363"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:5.0.0.3363
      - ghcr.io/epicmorg/testrail:5.0.0.3363
      - docker.io/epicmorg/testrail:5.0.0.3363
