services:
  app:
    image: "epicmorg/fisheye-crucible:2.3.3"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:2.3.3
  app-jdk6:
    image: "epicmorg/fisheye-crucible:2.3.3-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:2.3.3-jdk6
