services:
  app:
    image: "epicmorg/bamboo:9.2.16"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.2.16
      - docker.io/epicmorg/bamboo:9.2.16-jdk11
      - quay.io/epicmorg/bamboo:9.2.16
      - quay.io/epicmorg/bamboo:9.2.16-jdk11
      - ghcr.io/epicmorg/bamboo:9.2.16
      - ghcr.io/epicmorg/bamboo:9.2.16-jdk11
