services:
  app:
    image: "epicmorg/testrail:auth-ad-5.2.0.3451"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ad-5.2.0.3451
      - ghcr.io/epicmorg/testrail:auth-ad-5.2.0.3451
      - docker.io/epicmorg/testrail:auth-ad-5.2.0.3451
