services:
  app:
    image: "epicmorg/ansible:2.16"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/ansible:2.16
      - ghcr.io/epicmorg/ansible:2.16
      - docker.io/epicmorg/ansible:2.16
      - quay.io/epicmorg/ansible:2.16.19
      - ghcr.io/epicmorg/ansible:2.16.19
      - docker.io/epicmorg/ansible:2.16.19
