services:
  app:
    image: "epicmorg/confluence:6.14.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.14.1
      - docker.io/epicmorg/confluence:6.14.1-jdk8
      - quay.io/epicmorg/confluence:6.14.1
      - quay.io/epicmorg/confluence:6.14.1-jdk8
      - ghcr.io/epicmorg/confluence:6.14.1
      - ghcr.io/epicmorg/confluence:6.14.1-jdk8
