services:
  app:
    image: "epicmorg/bitbucket-mesh:2.0.28"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket-mesh:2.0.28
      - docker.io/epicmorg/bitbucket-mesh:2.0.28-jdk11
      - quay.io/epicmorg/bitbucket-mesh:2.0.28
      - quay.io/epicmorg/bitbucket-mesh:2.0.28-jdk11
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.28
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.28-jdk11
