services:
  app:
    image: "epicmorg/github-runner:php8.4"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/github-runner:php8.4
      - quay.io/epicmorg/github-runner:php8.4
      - ghcr.io/epicmorg/github-runner:php8.4
