services:
  app:
    image: "epicmorg/testrail:6.0.0.4140"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.0.0.4140
      - ghcr.io/epicmorg/testrail:6.0.0.4140
      - docker.io/epicmorg/testrail:6.0.0.4140
