services:
  app:
    image: "epicmorg/confluence:6.13.20"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.13.20
      - docker.io/epicmorg/confluence:6.13.20-jdk8
      - quay.io/epicmorg/confluence:6.13.20
      - quay.io/epicmorg/confluence:6.13.20-jdk8
      - ghcr.io/epicmorg/confluence:6.13.20
      - ghcr.io/epicmorg/confluence:6.13.20-jdk8
