services:
  app:
    image: "epicmorg/confluence:5.6.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:5.6.1
      - docker.io/epicmorg/confluence:5.6.1-jdk7
      - quay.io/epicmorg/confluence:5.6.1
      - quay.io/epicmorg/confluence:5.6.1-jdk7
      - ghcr.io/epicmorg/confluence:5.6.1
      - ghcr.io/epicmorg/confluence:5.6.1-jdk7
