services:
  app:
    image: "epicmorg/testrail:auth-ldap-7.0.2.1014"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-7.0.2.1014
      - ghcr.io/epicmorg/testrail:auth-ldap-7.0.2.1014
      - docker.io/epicmorg/testrail:auth-ldap-7.0.2.1014
