services:
  app:
    image: "epicmorg/confluence:6.6.13"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.6.13
      - docker.io/epicmorg/confluence:6.6.13-jdk8
      - quay.io/epicmorg/confluence:6.6.13
      - quay.io/epicmorg/confluence:6.6.13-jdk8
      - ghcr.io/epicmorg/confluence:6.6.13
      - ghcr.io/epicmorg/confluence:6.6.13-jdk8
