services:
  app:
    image: "epicmorg/bitbucket:10.2.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:10.2.3
      - docker.io/epicmorg/bitbucket:10.2.3-jdk21
      - quay.io/epicmorg/bitbucket:10.2.3
      - quay.io/epicmorg/bitbucket:10.2.3-jdk21
      - ghcr.io/epicmorg/bitbucket:10.2.3
      - ghcr.io/epicmorg/bitbucket:10.2.3-jdk21
