services:
  app:
    image: "epicmorg/confluence:6.6.15"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.6.15
      - docker.io/epicmorg/confluence:6.6.15-jdk8
      - quay.io/epicmorg/confluence:6.6.15
      - quay.io/epicmorg/confluence:6.6.15-jdk8
      - ghcr.io/epicmorg/confluence:6.6.15
      - ghcr.io/epicmorg/confluence:6.6.15-jdk8
