services:
  app:
    image: "epicmorg/bitbucket:3.11.0"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:3.11.0
  app-jdk8:
    image: "epicmorg/bitbucket:3.11.0-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:3.11.0-jdk8