services:
  app:
    image: "epicmorg/zabbix-java-gateway:7.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-java-gateway:7.4
      - quay.io/epicmorg/zabbix-java-gateway:7.4
      - ghcr.io/epicmorg/zabbix-java-gateway:7.4
