services:
  app:
    image: "epicmorg/bitbucket:4.14.6"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:4.14.6
      - docker.io/epicmorg/bitbucket:4.14.6-jdk8
      - quay.io/epicmorg/bitbucket:4.14.6
      - quay.io/epicmorg/bitbucket:4.14.6-jdk8
      - ghcr.io/epicmorg/bitbucket:4.14.6
      - ghcr.io/epicmorg/bitbucket:4.14.6-jdk8
