services:
  app:
    image: "epicmorg/zabbix-web-apache-mysql:5.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-web-apache-mysql:5.4
      - quay.io/epicmorg/zabbix-web-apache-mysql:5.4
      - ghcr.io/epicmorg/zabbix-web-apache-mysql:5.4
