# default JDK (Dockerfile) = jdk21; the extra JDK is built from Dockerfile.jdk17
services:
  app:
    image: "epicmorg/bitbucket:9.6.0"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/bitbucket:9.6.0
      - quay.io/epicmorg/bitbucket:9.6.0
      - ghcr.io/epicmorg/bitbucket:9.6.0
  app-jdk17:
    image: "epicmorg/bitbucket:9.6.0-jdk17"
    build:
      context: .
      dockerfile: Dockerfile.jdk17
    x-mirrors:
      - docker.io/epicmorg/bitbucket:9.6.0-jdk17
      - quay.io/epicmorg/bitbucket:9.6.0-jdk17
      - ghcr.io/epicmorg/bitbucket:9.6.0-jdk17
  app-jdk21:
    image: "epicmorg/bitbucket:9.6.0-jdk21"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/bitbucket:9.6.0-jdk21
      - quay.io/epicmorg/bitbucket:9.6.0-jdk21
      - ghcr.io/epicmorg/bitbucket:9.6.0-jdk21
