services:
  app:
    image: "epicmorg/postgres:9.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/postgres:9.3
      - ghcr.io/epicmorg/postgres:9.3
      - docker.io/epicmorg/postgres:9.3
