services:
  app:
    image: "epicmorg/testrail:auth-ldap-5.4.1.3669"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-5.4.1.3669
      - ghcr.io/epicmorg/testrail:auth-ldap-5.4.1.3669
      - docker.io/epicmorg/testrail:auth-ldap-5.4.1.3669
