services:
  app:
    image: "epicmorg/teamcity-agent:php8.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/teamcity-agent:php8.0
      - ghcr.io/epicmorg/teamcity-agent:php8.0
      - docker.io/epicmorg/teamcity-agent:php8.0
