services:
  app:
    image: "epicmorg/apache2:php8.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/apache2:php8.5
      - ghcr.io/epicmorg/apache2:php8.5
      - docker.io/epicmorg/apache2:php8.5
