services:
  app:
    image: "epicmorg/teamcity-agent:node18"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/teamcity-agent:node18
      - ghcr.io/epicmorg/teamcity-agent:node18
      - docker.io/epicmorg/teamcity-agent:node18
