services:
  qbt:
    image: "epicmorg/qbittorrent:5.0.4"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/qbittorrent:5.0.4
      - quay.io/epicmorg/qbittorrent:5.0.4
      - ghcr.io/epicmorg/qbittorrent:5.0.4
  qbt-libtorrent2:
    image: "epicmorg/qbittorrent:5.0.4-libtorrent2.0.11"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/qbittorrent:5.0.4-libtorrent2.0.11
      - quay.io/epicmorg/qbittorrent:5.0.4-libtorrent2.0.11
      - ghcr.io/epicmorg/qbittorrent:5.0.4-libtorrent2.0.11
  qbt-libtorrent1:
    image: "epicmorg/qbittorrent:5.0.4-libtorrent1.2.20"
    build:
      context: .
      dockerfile: ./Dockerfile.libtorrent1
    x-mirrors:
      - docker.io/epicmorg/qbittorrent:5.0.4-libtorrent1.2.20
      - quay.io/epicmorg/qbittorrent:5.0.4-libtorrent1.2.20
      - ghcr.io/epicmorg/qbittorrent:5.0.4-libtorrent1.2.20
