services:
  app:
    image: "epicmorg/crowd:7.1.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:7.1.4
      - docker.io/epicmorg/crowd:7.1.4-jdk21
      - quay.io/epicmorg/crowd:7.1.4
      - quay.io/epicmorg/crowd:7.1.4-jdk21
      - ghcr.io/epicmorg/crowd:7.1.4
      - ghcr.io/epicmorg/crowd:7.1.4-jdk21
