[program:apache2]
command=/bin/bash -c "/usr/bin/docker-entrypoint.sh"
autostart=true
autorestart=true
startretries=3
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopsignal=WINCH
stopwaitsecs=30
