services:
  app:
    image: "epicmorg/bamboo:9.2.13"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.2.13
      - docker.io/epicmorg/bamboo:9.2.13-jdk11
      - quay.io/epicmorg/bamboo:9.2.13
      - quay.io/epicmorg/bamboo:9.2.13-jdk11
      - ghcr.io/epicmorg/bamboo:9.2.13
      - ghcr.io/epicmorg/bamboo:9.2.13-jdk11
