services:
  app:
    image: "epicmorg/testrail:auth-ldap-5.2.0.3452"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-5.2.0.3452
      - ghcr.io/epicmorg/testrail:auth-ldap-5.2.0.3452
      - docker.io/epicmorg/testrail:auth-ldap-5.2.0.3452
