atlassian_root: "{{ playbook_dir }}/../../linux/ecosystem/apps/atlassian"
# Defaults
target_directory_crowd_0: "{{ atlassian_root }}/crowd/0"
target_directory_crowd_1: "{{ atlassian_root }}/crowd/1"
target_directory_crowd_2: "{{ atlassian_root }}/crowd/2"
target_directory_crowd_3: "{{ atlassian_root }}/crowd/3"
target_directory_crowd_4: "{{ atlassian_root }}/crowd/4"
target_directory_crowd_5: "{{ atlassian_root }}/crowd/5"
target_directory_crowd_6: "{{ atlassian_root }}/crowd/6"
target_directory_crowd_7: "{{ atlassian_root }}/crowd/7"
