services:
  app:
    image: "epicmorg/bamboo:12.0.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:12.0.2
      - docker.io/epicmorg/bamboo:12.0.2-jdk21
      - quay.io/epicmorg/bamboo:12.0.2
      - quay.io/epicmorg/bamboo:12.0.2-jdk21
      - ghcr.io/epicmorg/bamboo:12.0.2
      - ghcr.io/epicmorg/bamboo:12.0.2-jdk21
