services:
  app:
    image: "epicmorg/testrail:5.5.0.3735"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:5.5.0.3735
      - ghcr.io/epicmorg/testrail:5.5.0.3735
      - docker.io/epicmorg/testrail:5.5.0.3735
