services:
  app:
    image: "epicmorg/confluence:6.13.17"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.13.17
      - docker.io/epicmorg/confluence:6.13.17-jdk8
      - quay.io/epicmorg/confluence:6.13.17
      - quay.io/epicmorg/confluence:6.13.17-jdk8
      - ghcr.io/epicmorg/confluence:6.13.17
      - ghcr.io/epicmorg/confluence:6.13.17-jdk8
