services:
  app:
    image: "epicmorg/testrail:auth-ldap-6.2.1.1003"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-6.2.1.1003
      - ghcr.io/epicmorg/testrail:auth-ldap-6.2.1.1003
      - docker.io/epicmorg/testrail:auth-ldap-6.2.1.1003
