services:
  app:
    image: "epicmorg/crowd:0.3.1"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:0.3.1
  app-jdk6:
    image: "epicmorg/crowd:0.3.1-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:0.3.1-jdk6
