services:
  app:
    image: "epicmorg/fisheye-crucible:4.5.1"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:4.5.1
  app-jdk8:
    image: "epicmorg/fisheye-crucible:4.5.1-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:4.5.1-jdk8
