services:
  app:
    image: "epicmorg/nginx:1.26-php8.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/nginx:1.26-php8.0
      - ghcr.io/epicmorg/nginx:1.26-php8.0
      - docker.io/epicmorg/nginx:1.26-php8.0
