services:
  app:
    image: "epicmorg/crowd:3.2.11"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:3.2.11
      - docker.io/epicmorg/crowd:3.2.11-jdk8
      - quay.io/epicmorg/crowd:3.2.11
      - quay.io/epicmorg/crowd:3.2.11-jdk8
      - ghcr.io/epicmorg/crowd:3.2.11
      - ghcr.io/epicmorg/crowd:3.2.11-jdk8
