services:
  app:
    image: "epicmorg/mongo:1.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/mongo:1.2
      - ghcr.io/epicmorg/mongo:1.2
      - docker.io/epicmorg/mongo:1.2
      - quay.io/epicmorg/mongo:1.2.5
      - ghcr.io/epicmorg/mongo:1.2.5
      - docker.io/epicmorg/mongo:1.2.5
