services:
  app:
    image: "epicmorg/nextcloud:15"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - quay.io/epicmorg/nextcloud:15
      - ghcr.io/epicmorg/nextcloud:15
      - docker.io/epicmorg/nextcloud:15
