services:
  app:
    image: "epicmorg/confluence:6.0.2"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:6.0.2
  app-jdk8:
    image: "epicmorg/confluence:6.0.2-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:6.0.2-jdk8
