services:
  app:
    image: "epicmorg/postgres:13"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/postgres:13
      - ghcr.io/epicmorg/postgres:13
      - docker.io/epicmorg/postgres:13
