services:
  app:
    image: "epicmorg/git-lfs:2.10"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/git-lfs:2.10
      - ghcr.io/epicmorg/git-lfs:2.10
      - docker.io/epicmorg/git-lfs:2.10
