services:
  app:
    image: "epicmorg/redis:8.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/redis:8.2
      - ghcr.io/epicmorg/redis:8.2
      - docker.io/epicmorg/redis:8.2
      - quay.io/epicmorg/redis:8.2.10
      - ghcr.io/epicmorg/redis:8.2.10
      - docker.io/epicmorg/redis:8.2.10
