services:
  app:
    image: "epicmorg/testrail:7.5.2.1002"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:7.5.2.1002
      - ghcr.io/epicmorg/testrail:7.5.2.1002
      - docker.io/epicmorg/testrail:7.5.2.1002
