services:
  app:
    image: "epicmorg/fisheye-crucible:4.9.8"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/fisheye-crucible:4.9.8
      - docker.io/epicmorg/fisheye-crucible:4.9.8-jdk8
      - quay.io/epicmorg/fisheye-crucible:4.9.8
      - quay.io/epicmorg/fisheye-crucible:4.9.8-jdk8
      - ghcr.io/epicmorg/fisheye-crucible:4.9.8
      - ghcr.io/epicmorg/fisheye-crucible:4.9.8-jdk8
