services:
  app:
    image: "epicmorg/vscode-server:android"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/vscode-server:android
      - quay.io/epicmorg/vscode-server:android
      - ghcr.io/epicmorg/vscode-server:android
