services:
  app:
    image: "epicmorg/fisheye-crucible:4.7.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/fisheye-crucible:4.7.3
      - docker.io/epicmorg/fisheye-crucible:4.7.3-jdk8
      - quay.io/epicmorg/fisheye-crucible:4.7.3
      - quay.io/epicmorg/fisheye-crucible:4.7.3-jdk8
      - ghcr.io/epicmorg/fisheye-crucible:4.7.3
      - ghcr.io/epicmorg/fisheye-crucible:4.7.3-jdk8
