services:
  app:
    image: "epicmorg/nginx:1.30-php7.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/nginx:1.30-php7.4
      - ghcr.io/epicmorg/nginx:1.30-php7.4
      - docker.io/epicmorg/nginx:1.30-php7.4
