services:
  app:
    image: "epicmorg/jira:9.1.0"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:9.1.0
  app-jdk8:
    image: "epicmorg/jira:9.1.0-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:9.1.0-jdk8
  app-jdk11:
    image: "epicmorg/jira:9.1.0-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - quay.io/epicmorg/jira:9.1.0-jdk11
