services:
  app:
    image: "epicmorg/php:7.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/php:7.1
      - ghcr.io/epicmorg/php:7.1
      - docker.io/epicmorg/php:7.1
