services:
  app:
    image: "epicmorg/perforce:r23.2"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/perforce:r23.2
      - quay.io/epicmorg/perforce:r23.2
      - ghcr.io/epicmorg/perforce:r23.2