services:
  app:
    image: "epicmorg/teamcity-server:2022.04.7"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - quay.io/epicmorg/teamcity-server:2022.04.7
      - ghcr.io/epicmorg/teamcity-server:2022.04.7
