services:
  app:
    image: "epicmorg/bitbucket:2.9.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:2.9.5
      - docker.io/epicmorg/bitbucket:2.9.5-jdk7
      - quay.io/epicmorg/bitbucket:2.9.5
      - quay.io/epicmorg/bitbucket:2.9.5-jdk7
      - ghcr.io/epicmorg/bitbucket:2.9.5
      - ghcr.io/epicmorg/bitbucket:2.9.5-jdk7
