services:
  app:
    image: "epicmorg/bitbucket:5.4.7"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:5.4.7
  app-jdk8:
    image: "epicmorg/bitbucket:5.4.7-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:5.4.7-jdk8