services:
  app:
    image: "epicmorg/testrail:auth-ldap-5.0.0.3357"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-5.0.0.3357
      - ghcr.io/epicmorg/testrail:auth-ldap-5.0.0.3357
      - docker.io/epicmorg/testrail:auth-ldap-5.0.0.3357
