services:
  app:
    image: "epicmorg/teamcity-agent:php5.6"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/teamcity-agent:php5.6
      - ghcr.io/epicmorg/teamcity-agent:php5.6
      - docker.io/epicmorg/teamcity-agent:php5.6
