services:
  app:
    image: "epicmorg/teamcity-server:2026.2"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - docker.io/epicmorg/teamcity-server:2026.2
      - quay.io/epicmorg/teamcity-server:2026.2
      - ghcr.io/epicmorg/teamcity-server:2026.2
