services:
  app:
    image: "epicmorg/confluence:7.19.22"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/confluence:7.19.22
      - quay.io/epicmorg/confluence:7.19.22
      - ghcr.io/epicmorg/confluence:7.19.22
  app-jdk8:
    image: "epicmorg/confluence:7.19.22-jdk8"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/confluence:7.19.22-jdk8
      - quay.io/epicmorg/confluence:7.19.22-jdk8
      - ghcr.io/epicmorg/confluence:7.19.22-jdk8
  app-jdk11:
    image: "epicmorg/confluence:7.19.22-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - docker.io/epicmorg/confluence:7.19.22-jdk11
      - quay.io/epicmorg/confluence:7.19.22-jdk11
      - ghcr.io/epicmorg/confluence:7.19.22-jdk11
