services:
  app:
    image: "epicmorg/webtlo:4.5.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/webtlo:4.5.1
      - ghcr.io/epicmorg/webtlo:4.5.1
      - docker.io/epicmorg/webtlo:4.5.1
