services:
  app:
    image: "epicmorg/nginx:1.25-php7.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/nginx:1.25-php7.1
      - ghcr.io/epicmorg/nginx:1.25-php7.1
      - docker.io/epicmorg/nginx:1.25-php7.1
