services:
  app:
    image: "epicmorg/sentry:latest"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/sentry:latest
      - quay.io/epicmorg/sentry:latest
      - ghcr.io/epicmorg/sentry:latest
