services:
  app:
    image: "epicmorg/crowd:6.0.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:6.0.1
      - docker.io/epicmorg/crowd:6.0.1-jdk17
      - quay.io/epicmorg/crowd:6.0.1
      - quay.io/epicmorg/crowd:6.0.1-jdk17
      - ghcr.io/epicmorg/crowd:6.0.1
      - ghcr.io/epicmorg/crowd:6.0.1-jdk17
