services:
  app:
    image: "epicmorg/bitbucket-mesh:2.0.33"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket-mesh:2.0.33
      - docker.io/epicmorg/bitbucket-mesh:2.0.33-jdk11
      - quay.io/epicmorg/bitbucket-mesh:2.0.33
      - quay.io/epicmorg/bitbucket-mesh:2.0.33-jdk11
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.33
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.33-jdk11
