services:
  app:
    image: "epicmorg/gitlab-runner:node8"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/gitlab-runner:node8
      - quay.io/epicmorg/gitlab-runner:node8
      - ghcr.io/epicmorg/gitlab-runner:node8
