services:
  app:
    image: "epicmorg/debian:sid-light"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - quay.io/epicmorg/debian:sid-light
      - ghcr.io/epicmorg/debian:sid-light
