services:
  app:
    image: "epicmorg/git-lfs:2.12"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/git-lfs:2.12
      - ghcr.io/epicmorg/git-lfs:2.12
      - docker.io/epicmorg/git-lfs:2.12
