services:
  app:
    image: "epicmorg/astralinux:1.7-develop"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/astralinux:1.7-develop
      - ghcr.io/epicmorg/astralinux:1.7-develop
