services:
  app:
    image: "epicmorg/bitbucket:8.19.24"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:8.19.24
  app-jdk17:
    image: "epicmorg/bitbucket:8.19.24-jdk17"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:8.19.24-jdk17
