services:
  app:
    image: "epicmorg/confluence:6.5.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.5.0
      - docker.io/epicmorg/confluence:6.5.0-jdk8
      - quay.io/epicmorg/confluence:6.5.0
      - quay.io/epicmorg/confluence:6.5.0-jdk8
      - ghcr.io/epicmorg/confluence:6.5.0
      - ghcr.io/epicmorg/confluence:6.5.0-jdk8
