services:
  app:
    image: "epicmorg/confluence:5.6.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:5.6.3
      - docker.io/epicmorg/confluence:5.6.3-jdk7
      - quay.io/epicmorg/confluence:5.6.3
      - quay.io/epicmorg/confluence:5.6.3-jdk7
      - ghcr.io/epicmorg/confluence:5.6.3
      - ghcr.io/epicmorg/confluence:5.6.3-jdk7
