services:
  app:
    image: "epicmorg/testrail:auth-ldap-4.0.3.3270"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-4.0.3.3270
      - ghcr.io/epicmorg/testrail:auth-ldap-4.0.3.3270
      - docker.io/epicmorg/testrail:auth-ldap-4.0.3.3270
