services:
  app:
    image: "epicmorg/bamboo:8.1.10"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:8.1.10
      - docker.io/epicmorg/bamboo:8.1.10-jdk11
      - quay.io/epicmorg/bamboo:8.1.10
      - quay.io/epicmorg/bamboo:8.1.10-jdk11
      - ghcr.io/epicmorg/bamboo:8.1.10
      - ghcr.io/epicmorg/bamboo:8.1.10-jdk11
