services:
  app:
    image: "epicmorg/redis:8.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/redis:8.0
      - ghcr.io/epicmorg/redis:8.0
      - docker.io/epicmorg/redis:8.0
      - quay.io/epicmorg/redis:8.0.6
      - ghcr.io/epicmorg/redis:8.0.6
      - docker.io/epicmorg/redis:8.0.6
