services:
  app:
    image: "epicmorg/crowd:2.0.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:2.0.4
      - docker.io/epicmorg/crowd:2.0.4-jdk6
      - quay.io/epicmorg/crowd:2.0.4
      - quay.io/epicmorg/crowd:2.0.4-jdk6
      - ghcr.io/epicmorg/crowd:2.0.4
      - ghcr.io/epicmorg/crowd:2.0.4-jdk6
