services:
  app:
    image: "epicmorg/bitbucket-mesh:2.0.34"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket-mesh:2.0.34
      - docker.io/epicmorg/bitbucket-mesh:2.0.34-jdk11
      - quay.io/epicmorg/bitbucket-mesh:2.0.34
      - quay.io/epicmorg/bitbucket-mesh:2.0.34-jdk11
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.34
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.34-jdk11
