services:
  app:
    image: "epicmorg/jira:7.5.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/jira:7.5.3
      - docker.io/epicmorg/jira:7.5.3-jdk8
      - quay.io/epicmorg/jira:7.5.3
      - quay.io/epicmorg/jira:7.5.3-jdk8
      - ghcr.io/epicmorg/jira:7.5.3
      - ghcr.io/epicmorg/jira:7.5.3-jdk8
