services:
  app:
    image: "epicmorg/confluence:6.6.16"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:6.6.16
  app-jdk8:
    image: "epicmorg/confluence:6.6.16-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:6.6.16-jdk8
