services:
  app:
    image: "epicmorg/testrail:3.1.0.3127"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:3.1.0.3127
      - ghcr.io/epicmorg/testrail:3.1.0.3127
      - docker.io/epicmorg/testrail:3.1.0.3127
