services:
  app:
    image: "epicmorg/zabbix-java-gateway:6.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-java-gateway:6.4
      - quay.io/epicmorg/zabbix-java-gateway:6.4
      - ghcr.io/epicmorg/zabbix-java-gateway:6.4
