services:
  app:
    image: "epicmorg/crowd:3.2.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:3.2.5
      - docker.io/epicmorg/crowd:3.2.5-jdk8
      - quay.io/epicmorg/crowd:3.2.5
      - quay.io/epicmorg/crowd:3.2.5-jdk8
      - ghcr.io/epicmorg/crowd:3.2.5
      - ghcr.io/epicmorg/crowd:3.2.5-jdk8
