services:
  app:
    image: "epicmorg/testrail:auth-ldap-5.6.0.3861"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-5.6.0.3861
      - ghcr.io/epicmorg/testrail:auth-ldap-5.6.0.3861
      - docker.io/epicmorg/testrail:auth-ldap-5.6.0.3861
