services:
  app:
    image: "epicmorg/enodia:1.1.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/enodia:1.1.1
      - ghcr.io/epicmorg/enodia:1.1.1
      - docker.io/epicmorg/enodia:1.1.1

