services:
  app:
    image: "epicmorg/nodejs:5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/nodejs:5
      - ghcr.io/epicmorg/nodejs:5
      - docker.io/epicmorg/nodejs:5
