services:
  app:
    image: "epicmorg/bitbucket:4.14.9"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:4.14.9
  app-jdk8:
    image: "epicmorg/bitbucket:4.14.9-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:4.14.9-jdk8