services:
  app:
    image: "epicmorg/fisheye-crucible:4.0.4"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:4.0.4
  app-jdk8:
    image: "epicmorg/fisheye-crucible:4.0.4-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:4.0.4-jdk8
