services:
  app:
    image: "epicmorg/teamcity-agent:amxx-sdk-rc"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/teamcity-agent:amxx-sdk-rc
      - quay.io/epicmorg/teamcity-agent:amxx-sdk-rc
      - ghcr.io/epicmorg/teamcity-agent:amxx-sdk-rc
