services:
  app:
    image: "epicmorg/testrail:6.4.0.1284"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.4.0.1284
      - ghcr.io/epicmorg/testrail:6.4.0.1284
      - docker.io/epicmorg/testrail:6.4.0.1284
