services:
  app:
    image: "epicmorg/gitlab-runner:node23"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/gitlab-runner:node23
      - quay.io/epicmorg/gitlab-runner:node23
      - ghcr.io/epicmorg/gitlab-runner:node23
