services:
  app:
    image: "epicmorg/confluence:4.1.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:4.1.4
      - docker.io/epicmorg/confluence:4.1.4-jdk6
      - quay.io/epicmorg/confluence:4.1.4
      - quay.io/epicmorg/confluence:4.1.4-jdk6
      - ghcr.io/epicmorg/confluence:4.1.4
      - ghcr.io/epicmorg/confluence:4.1.4-jdk6
