atlassian_root: "{{ playbook_dir }}/../../linux/ecosystem/apps/atlassian"
# Defaults
target_directory_fisheye_2: "{{ atlassian_root }}/fisheye-crucible/2"
target_directory_fisheye_3: "{{ atlassian_root }}/fisheye-crucible/3"
target_directory_fisheye_4: "{{ atlassian_root }}/fisheye-crucible/4"