services:
  app:
    image: "epicmorg/fisheye-crucible:3.5.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/fisheye-crucible:3.5.5
      - docker.io/epicmorg/fisheye-crucible:3.5.5-jdk8
      - quay.io/epicmorg/fisheye-crucible:3.5.5
      - quay.io/epicmorg/fisheye-crucible:3.5.5-jdk8
      - ghcr.io/epicmorg/fisheye-crucible:3.5.5
      - ghcr.io/epicmorg/fisheye-crucible:3.5.5-jdk8
