services:
  app:
    image: "epicmorg/confluence:8.9.1"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:8.9.1
  app-jdk11:
    image: "epicmorg/confluence:8.9.1-jdk11"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:8.9.1-jdk11
  app-jdk17:
    image: "epicmorg/confluence:8.9.1-jdk17"
    build:
      context: .
      dockerfile: Dockerfile.jdk17
    x-mirrors:
      - quay.io/epicmorg/confluence:8.9.1-jdk17
