services:
  app:
    image: "epicmorg/nginx:1.29"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/nginx:1.29
      - ghcr.io/epicmorg/nginx:1.29
      - docker.io/epicmorg/nginx:1.29
