services:
  app:
    image: "epicmorg/bitbucket-mesh:2.0.37"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket-mesh:2.0.37
      - docker.io/epicmorg/bitbucket-mesh:2.0.37-jdk11
      - quay.io/epicmorg/bitbucket-mesh:2.0.37
      - quay.io/epicmorg/bitbucket-mesh:2.0.37-jdk11
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.37
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.37-jdk11
