services:
  app:
    image: "epicmorg/crucible:1.5.4"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crucible:1.5.4
  app-jdk6:
    image: "epicmorg/crucible:1.5.4-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crucible:1.5.4-jdk6
