services:
  app:
    image: "epicmorg/bitbucket:1.2.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:1.2.4
      - docker.io/epicmorg/bitbucket:1.2.4-jdk7
      - quay.io/epicmorg/bitbucket:1.2.4
      - quay.io/epicmorg/bitbucket:1.2.4-jdk7
      - ghcr.io/epicmorg/bitbucket:1.2.4
      - ghcr.io/epicmorg/bitbucket:1.2.4-jdk7
