services:
  app:
    image: "epicmorg/confluence:9.2.18"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/confluence:9.2.18
      - quay.io/epicmorg/confluence:9.2.18
      - ghcr.io/epicmorg/confluence:9.2.18
  app-jdk17:
    image: "epicmorg/confluence:9.2.18-jdk17"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/confluence:9.2.18-jdk17
      - quay.io/epicmorg/confluence:9.2.18-jdk17
      - ghcr.io/epicmorg/confluence:9.2.18-jdk17
  app-jdk21:
    image: "epicmorg/confluence:9.2.18-jdk21"
    build:
      context: .
      dockerfile: Dockerfile.jdk21
    x-mirrors:
      - docker.io/epicmorg/confluence:9.2.18-jdk21
      - quay.io/epicmorg/confluence:9.2.18-jdk21
      - ghcr.io/epicmorg/confluence:9.2.18-jdk21
