services:
  app:
    image: "epicmorg/confluence:5.5-OD-31-009"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:5.5-OD-31-009
      - docker.io/epicmorg/confluence:5.5-OD-31-009-jdk7
      - quay.io/epicmorg/confluence:5.5-OD-31-009
      - quay.io/epicmorg/confluence:5.5-OD-31-009-jdk7
      - ghcr.io/epicmorg/confluence:5.5-OD-31-009
      - ghcr.io/epicmorg/confluence:5.5-OD-31-009-jdk7
