services:
  app:
    image: "epicmorg/testrail:auth-ldap-5.0.2.3372"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-5.0.2.3372
      - ghcr.io/epicmorg/testrail:auth-ldap-5.0.2.3372
      - docker.io/epicmorg/testrail:auth-ldap-5.0.2.3372
