services:
  app:
    image: "epicmorg/teamcity-agent:ansible-2.12"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/teamcity-agent:ansible-2.12
      - ghcr.io/epicmorg/teamcity-agent:ansible-2.12
      - docker.io/epicmorg/teamcity-agent:ansible-2.12
      - quay.io/epicmorg/teamcity-agent:ansible-2.12.10
      - ghcr.io/epicmorg/teamcity-agent:ansible-2.12.10
      - docker.io/epicmorg/teamcity-agent:ansible-2.12.10
