services:
  app:
    image: "epicmorg/confluence:7.0.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:7.0.5
      - docker.io/epicmorg/confluence:7.0.5-jdk8
      - quay.io/epicmorg/confluence:7.0.5
      - quay.io/epicmorg/confluence:7.0.5-jdk8
      - ghcr.io/epicmorg/confluence:7.0.5
      - ghcr.io/epicmorg/confluence:7.0.5-jdk8
