services:
  app:
    image: "epicmorg/fisheye:1.5.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/fisheye:1.5.1
      - docker.io/epicmorg/fisheye:1.5.1-jdk6
      - quay.io/epicmorg/fisheye:1.5.1
      - quay.io/epicmorg/fisheye:1.5.1-jdk6
      - ghcr.io/epicmorg/fisheye:1.5.1
      - ghcr.io/epicmorg/fisheye:1.5.1-jdk6
