atlassian_root: "{{ playbook_dir }}/../../linux/ecosystem/apps/atlassian"
# Defaults
target_directory_bitbucket_1: "{{ atlassian_root }}/bitbucket/1"
target_directory_bitbucket_2: "{{ atlassian_root }}/bitbucket/2"
target_directory_bitbucket_3: "{{ atlassian_root }}/bitbucket/3"
target_directory_bitbucket_4: "{{ atlassian_root }}/bitbucket/4"
target_directory_bitbucket_5: "{{ atlassian_root }}/bitbucket/5"
target_directory_bitbucket_6: "{{ atlassian_root }}/bitbucket/6"
target_directory_bitbucket_7: "{{ atlassian_root }}/bitbucket/7"
target_directory_bitbucket_8: "{{ atlassian_root }}/bitbucket/8"
target_directory_bitbucket_9: "{{ atlassian_root }}/bitbucket/9"
target_directory_bitbucket_10: "{{ atlassian_root }}/bitbucket/10"
