services:
  app:
    image: "epicmorg/git:2.28"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/git:2.28
      - ghcr.io/epicmorg/git:2.28
      - docker.io/epicmorg/git:2.28
