services:
  app:
    image: "epicmorg/apache2:php7.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/apache2:php7.0
      - ghcr.io/epicmorg/apache2:php7.0
      - docker.io/epicmorg/apache2:php7.0
