services:
  app:
    image: "epicmorg/bamboo:9.1.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.1.2
      - docker.io/epicmorg/bamboo:9.1.2-jdk11
      - quay.io/epicmorg/bamboo:9.1.2
      - quay.io/epicmorg/bamboo:9.1.2-jdk11
      - ghcr.io/epicmorg/bamboo:9.1.2
      - ghcr.io/epicmorg/bamboo:9.1.2-jdk11
