services:
  app:
    image: "epicmorg/git:2.13"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/git:2.13
      - ghcr.io/epicmorg/git:2.13
      - docker.io/epicmorg/git:2.13
