services:
  app:
    image: "epicmorg/fisheye:1.5.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/fisheye:1.5.3
      - docker.io/epicmorg/fisheye:1.5.3-jdk6
      - quay.io/epicmorg/fisheye:1.5.3
      - quay.io/epicmorg/fisheye:1.5.3-jdk6
      - ghcr.io/epicmorg/fisheye:1.5.3
      - ghcr.io/epicmorg/fisheye:1.5.3-jdk6
