services:
  app:
    image: "epicmorg/testrail:6.5.6.1014"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.5.6.1014
      - ghcr.io/epicmorg/testrail:6.5.6.1014
      - docker.io/epicmorg/testrail:6.5.6.1014
