services:
  app:
    image: "epicmorg/bitbucket:4.14.10"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:4.14.10
      - docker.io/epicmorg/bitbucket:4.14.10-jdk8
      - quay.io/epicmorg/bitbucket:4.14.10
      - quay.io/epicmorg/bitbucket:4.14.10-jdk8
      - ghcr.io/epicmorg/bitbucket:4.14.10
      - ghcr.io/epicmorg/bitbucket:4.14.10-jdk8
