services:
  app:
    image: "epicmorg/ansible:2.18"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/ansible:2.18
      - ghcr.io/epicmorg/ansible:2.18
      - docker.io/epicmorg/ansible:2.18
      - quay.io/epicmorg/ansible:2.18.19
      - ghcr.io/epicmorg/ansible:2.18.19
      - docker.io/epicmorg/ansible:2.18.19
