atlassian_root: "{{ playbook_dir }}/../../linux/ecosystem/apps/atlassian"
# Defaults
target_directory_jira_4: "{{ atlassian_root }}/jira/4"
target_directory_jira_5: "{{ atlassian_root }}/jira/5"
target_directory_jira_6: "{{ atlassian_root }}/jira/6"
target_directory_jira_7: "{{ atlassian_root }}/jira/7"
target_directory_jira_8: "{{ atlassian_root }}/jira/8"
target_directory_jira_9: "{{ atlassian_root }}/jira/9"
target_directory_jira_10: "{{ atlassian_root }}/jira/10"
target_directory_jira_11: "{{ atlassian_root }}/jira/11"
