services:
  app:
    image: "epicmorg/crowd:2.0.1"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:2.0.1
  app-jdk6:
    image: "epicmorg/crowd:2.0.1-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:2.0.1-jdk6
  app-jdk7:
    image: "epicmorg/crowd:2.0.1-jdk7"
    build:
      context: .
      dockerfile: Dockerfile.jdk7
    x-mirrors:
      - quay.io/epicmorg/crowd:2.0.1-jdk7
