services:
  app:
    image: "epicmorg/zabbix-proxy-sqlite3:7.2"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - docker.io/epicmorg/zabbix-proxy-sqlite3:7.2
      - quay.io/epicmorg/zabbix-proxy-sqlite3:7.2
      - ghcr.io/epicmorg/zabbix-proxy-sqlite3:7.2
