services:
  app:
    image: "epicmorg/confluence:6.13.19"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.13.19
      - docker.io/epicmorg/confluence:6.13.19-jdk8
      - quay.io/epicmorg/confluence:6.13.19
      - quay.io/epicmorg/confluence:6.13.19-jdk8
      - ghcr.io/epicmorg/confluence:6.13.19
      - ghcr.io/epicmorg/confluence:6.13.19-jdk8
