services:
  app:
    image: "epicmorg/testrail:5.6.0.3856"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:5.6.0.3856
      - ghcr.io/epicmorg/testrail:5.6.0.3856
      - docker.io/epicmorg/testrail:5.6.0.3856
