services:
  app:
    image: "epicmorg/postgres:9.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/postgres:9.5
      - ghcr.io/epicmorg/postgres:9.5
      - docker.io/epicmorg/postgres:9.5
