services:
  app:
    image: "epicmorg/confluence:6.0.7"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.0.7
      - docker.io/epicmorg/confluence:6.0.7-jdk8
      - quay.io/epicmorg/confluence:6.0.7
      - quay.io/epicmorg/confluence:6.0.7-jdk8
      - ghcr.io/epicmorg/confluence:6.0.7
      - ghcr.io/epicmorg/confluence:6.0.7-jdk8
