services:
  app:
    image: "epicmorg/testrail:6.2.3.1114"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.2.3.1114
      - ghcr.io/epicmorg/testrail:6.2.3.1114
      - docker.io/epicmorg/testrail:6.2.3.1114
