services:
  app:
    image: "epicmorg/crowd:6.0.2"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:6.0.2
  app-jdk17:
    image: "epicmorg/crowd:6.0.2-jdk17"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/crowd:6.0.2-jdk17
