services:
  app:
    image: "epicmorg/gitlab-runner:node5"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/gitlab-runner:node5
      - quay.io/epicmorg/gitlab-runner:node5
      - ghcr.io/epicmorg/gitlab-runner:node5
