services:
  app:
    image: "epicmorg/bitbucket:8.17.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:8.17.2
      - docker.io/epicmorg/bitbucket:8.17.2-jdk17
      - quay.io/epicmorg/bitbucket:8.17.2
      - quay.io/epicmorg/bitbucket:8.17.2-jdk17
      - ghcr.io/epicmorg/bitbucket:8.17.2
      - ghcr.io/epicmorg/bitbucket:8.17.2-jdk17
