services:
  app:
    image: "epicmorg/fisheye-crucible:3.9.0"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:3.9.0
  app-jdk8:
    image: "epicmorg/fisheye-crucible:3.9.0-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:3.9.0-jdk8
