services:
  app:
    image: "epicmorg/zabbix-java-gateway:4.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-java-gateway:4.0
      - quay.io/epicmorg/zabbix-java-gateway:4.0
      - ghcr.io/epicmorg/zabbix-java-gateway:4.0
