services:
  app:
    image: "epicmorg/bitbucket:3.4.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:3.4.5
      - docker.io/epicmorg/bitbucket:3.4.5-jdk8
      - quay.io/epicmorg/bitbucket:3.4.5
      - quay.io/epicmorg/bitbucket:3.4.5-jdk8
      - ghcr.io/epicmorg/bitbucket:3.4.5
      - ghcr.io/epicmorg/bitbucket:3.4.5-jdk8
