services:
  app:
    image: "epicmorg/confluence:10.2.0"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:10.2.0
  app-jdk21:
    image: "epicmorg/confluence:10.2.0-jdk21"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:10.2.0-jdk21
