services:
  app:
    image: "epicmorg/confluence:10.2.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:10.2.0
      - docker.io/epicmorg/confluence:10.2.0-jdk21
      - quay.io/epicmorg/confluence:10.2.0
      - quay.io/epicmorg/confluence:10.2.0-jdk21
      - ghcr.io/epicmorg/confluence:10.2.0
      - ghcr.io/epicmorg/confluence:10.2.0-jdk21
