services:
  app:
    image: "epicmorg/crowd:5.3.7"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/crowd:5.3.7
      - quay.io/epicmorg/crowd:5.3.7
      - ghcr.io/epicmorg/crowd:5.3.7
  app-jdk8:
    image: "epicmorg/crowd:5.3.7-jdk8"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/crowd:5.3.7-jdk8
      - quay.io/epicmorg/crowd:5.3.7-jdk8
      - ghcr.io/epicmorg/crowd:5.3.7-jdk8
  app-jdk11:
    image: "epicmorg/crowd:5.3.7-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - docker.io/epicmorg/crowd:5.3.7-jdk11
      - quay.io/epicmorg/crowd:5.3.7-jdk11
      - ghcr.io/epicmorg/crowd:5.3.7-jdk11
