services:
  app:
    image: "epicmorg/bamboo:7.2.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:7.2.2
      - docker.io/epicmorg/bamboo:7.2.2-jdk8
      - quay.io/epicmorg/bamboo:7.2.2
      - quay.io/epicmorg/bamboo:7.2.2-jdk8
      - ghcr.io/epicmorg/bamboo:7.2.2
      - ghcr.io/epicmorg/bamboo:7.2.2-jdk8
