services:
  app:
    image: "epicmorg/bamboo:9.2.24"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.2.24
      - docker.io/epicmorg/bamboo:9.2.24-jdk11
      - quay.io/epicmorg/bamboo:9.2.24
      - quay.io/epicmorg/bamboo:9.2.24-jdk11
      - ghcr.io/epicmorg/bamboo:9.2.24
      - ghcr.io/epicmorg/bamboo:9.2.24-jdk11
