services:
  app:
    image: "epicmorg/jira:9.12.21"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:9.12.21
  app-jdk8:
    image: "epicmorg/jira:9.12.21-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:9.12.21-jdk8
  app-jdk11:
    image: "epicmorg/jira:9.12.21-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - quay.io/epicmorg/jira:9.12.21-jdk11
  app-jdk17:
    image: "epicmorg/jira:9.12.21-jdk17"
    build:
      context: .
      dockerfile: Dockerfile.jdk17
    x-mirrors:
      - quay.io/epicmorg/jira:9.12.21-jdk17