FROM zabbix/zabbix-server-mysql:ubuntu-latest
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y &&  apt install -y --allow-unauthenticated ca-certificates gnupg sudo apt-transport-https lsb-release apt-utils locales console-cyrillic wget curl htop mc tmux iftop cmatrix iputils-ping  cmatrix-xfont  lsof lynx fontconfig smbclient nano
