services:
  app:
    image: "epicmorg/bamboo:9.2.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.2.3
      - docker.io/epicmorg/bamboo:9.2.3-jdk11
      - quay.io/epicmorg/bamboo:9.2.3
      - quay.io/epicmorg/bamboo:9.2.3-jdk11
      - ghcr.io/epicmorg/bamboo:9.2.3
      - ghcr.io/epicmorg/bamboo:9.2.3-jdk11
