services:
  app:
    image: "epicmorg/crowd:2.9.7"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/crowd:2.9.7
      - quay.io/epicmorg/crowd:2.9.7
      - ghcr.io/epicmorg/crowd:2.9.7
  app-jdk6:
    image: "epicmorg/crowd:2.9.7-jdk6"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/crowd:2.9.7-jdk6
      - quay.io/epicmorg/crowd:2.9.7-jdk6
      - ghcr.io/epicmorg/crowd:2.9.7-jdk6
  app-jdk7:
    image: "epicmorg/crowd:2.9.7-jdk7"
    build:
      context: .
      dockerfile: Dockerfile.jdk7
    x-mirrors:
      - docker.io/epicmorg/crowd:2.9.7-jdk7
      - quay.io/epicmorg/crowd:2.9.7-jdk7
      - ghcr.io/epicmorg/crowd:2.9.7-jdk7
