services:
  app:
    image: "epicmorg/gitlab-runner:php7.1"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/gitlab-runner:php7.1
      - quay.io/epicmorg/gitlab-runner:php7.1
      - ghcr.io/epicmorg/gitlab-runner:php7.1
