services:
  app:
    image: "epicmorg/testrail:auth-ad-5.0.0.3364"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ad-5.0.0.3364
      - ghcr.io/epicmorg/testrail:auth-ad-5.0.0.3364
      - docker.io/epicmorg/testrail:auth-ad-5.0.0.3364
