services:
  app:
    image: "epicmorg/bitbucket-mesh:2.0.38"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket-mesh:2.0.38
      - docker.io/epicmorg/bitbucket-mesh:2.0.38-jdk11
      - quay.io/epicmorg/bitbucket-mesh:2.0.38
      - quay.io/epicmorg/bitbucket-mesh:2.0.38-jdk11
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.38
      - ghcr.io/epicmorg/bitbucket-mesh:2.0.38-jdk11
