services:
  app:
    image: "epicmorg/confluence:6.15.10"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.15.10
      - docker.io/epicmorg/confluence:6.15.10-jdk8
      - quay.io/epicmorg/confluence:6.15.10
      - quay.io/epicmorg/confluence:6.15.10-jdk8
      - ghcr.io/epicmorg/confluence:6.15.10
      - ghcr.io/epicmorg/confluence:6.15.10-jdk8
