services:
  app:
    image: "epicmorg/testrail:6.2.1.1005"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.2.1.1005
      - ghcr.io/epicmorg/testrail:6.2.1.1005
      - docker.io/epicmorg/testrail:6.2.1.1005
