services:
  app:
    image: "epicmorg/confluence:5.1.5"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:5.1.5
  app-jdk7:
    image: "epicmorg/confluence:5.1.5-jdk7"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:5.1.5-jdk7
