services:
  app:
    image: "epicmorg/astralinux:1.8-develop-light"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/astralinux:1.8-develop-light
      - ghcr.io/epicmorg/astralinux:1.8-develop-light
      - docker.io/epicmorg/astralinux:1.8-develop-light
