services:
  app:
    image: "epicmorg/zabbix-agent2:7.4"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-agent2:7.4
      - quay.io/epicmorg/zabbix-agent2:7.4
      - ghcr.io/epicmorg/zabbix-agent2:7.4
