services:
  app:
    image: "epicmorg/redis:8.8"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/redis:8.8
      - ghcr.io/epicmorg/redis:8.8
      - docker.io/epicmorg/redis:8.8
      - quay.io/epicmorg/redis:8.8.3
      - ghcr.io/epicmorg/redis:8.8.3
      - docker.io/epicmorg/redis:8.8.3
