services:
  app:
    image: "epicmorg/confluence:5.7.1"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:5.7.1
  app-jdk7:
    image: "epicmorg/confluence:5.7.1-jdk7"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:5.7.1-jdk7
  app-jdk8:
    image: "epicmorg/confluence:5.7.1-jdk8"
    build:
      context: .
      dockerfile: Dockerfile.jdk8
    x-mirrors:
      - quay.io/epicmorg/confluence:5.7.1-jdk8
