services:
  app:
    image: "epicmorg/testrail:6.7.2.1037"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.7.2.1037
      - ghcr.io/epicmorg/testrail:6.7.2.1037
      - docker.io/epicmorg/testrail:6.7.2.1037
