services:
  app:
    image: "epicmorg/testrail:9.0.0.1057"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:9.0.0.1057
      - ghcr.io/epicmorg/testrail:9.0.0.1057
      - docker.io/epicmorg/testrail:9.0.0.1057
