services:
  app:
    image: "epicmorg/testrail:6.1.1.1020"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:6.1.1.1020
      - ghcr.io/epicmorg/testrail:6.1.1.1020
      - docker.io/epicmorg/testrail:6.1.1.1020
