services:
  app:
    image: "epicmorg/bamboo:9.2.12"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.2.12
      - docker.io/epicmorg/bamboo:9.2.12-jdk11
      - quay.io/epicmorg/bamboo:9.2.12
      - quay.io/epicmorg/bamboo:9.2.12-jdk11
      - ghcr.io/epicmorg/bamboo:9.2.12
      - ghcr.io/epicmorg/bamboo:9.2.12-jdk11
