services:
  app:
    image: "epicmorg/crowd:0.4.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:0.4.2
      - docker.io/epicmorg/crowd:0.4.2-jdk6
      - quay.io/epicmorg/crowd:0.4.2
      - quay.io/epicmorg/crowd:0.4.2-jdk6
      - ghcr.io/epicmorg/crowd:0.4.2
      - ghcr.io/epicmorg/crowd:0.4.2-jdk6
