services:
  app:
    image: "epicmorg/teamcity-agent:node24"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/teamcity-agent:node24
      - ghcr.io/epicmorg/teamcity-agent:node24
      - docker.io/epicmorg/teamcity-agent:node24
