services:
  app:
    image: "epicmorg/testrail:auth-ldap-5.0.1.3370"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ldap-5.0.1.3370
      - ghcr.io/epicmorg/testrail:auth-ldap-5.0.1.3370
      - docker.io/epicmorg/testrail:auth-ldap-5.0.1.3370
