services:
  app:
    image: "epicmorg/jira:7.3.8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:7.3.8
  app-jdk8:
    image: "epicmorg/jira:7.3.8-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/jira:7.3.8-jdk8
