services:
  app:
    image: "epicmorg/crucible:1.1.1"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crucible:1.1.1
      - docker.io/epicmorg/crucible:1.1.1-jdk6
      - quay.io/epicmorg/crucible:1.1.1
      - quay.io/epicmorg/crucible:1.1.1-jdk6
      - ghcr.io/epicmorg/crucible:1.1.1
      - ghcr.io/epicmorg/crucible:1.1.1-jdk6
