services:
  app:
    image: "epicmorg/enodia:1.0.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/enodia:1.0.0-0
      - ghcr.io/epicmorg/enodia:1.0.0-0
      - docker.io/epicmorg/enodia:1.0.0-0
      - quay.io/epicmorg/enodia:1.0.0
      - ghcr.io/epicmorg/enodia:1.0.0
      - docker.io/epicmorg/enodia:1.0.0
