services:
  app:
    image: "epicmorg/confluence:4.3.6"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/confluence:4.3.6
      - quay.io/epicmorg/confluence:4.3.6
      - ghcr.io/epicmorg/confluence:4.3.6
  app-jdk6:
    image: "epicmorg/confluence:4.3.6-jdk6"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/confluence:4.3.6-jdk6
      - quay.io/epicmorg/confluence:4.3.6-jdk6
      - ghcr.io/epicmorg/confluence:4.3.6-jdk6
  app-jdk7:
    image: "epicmorg/confluence:4.3.6-jdk7"
    build:
      context: .
      dockerfile: Dockerfile.jdk7
    x-mirrors:
      - docker.io/epicmorg/confluence:4.3.6-jdk7
      - quay.io/epicmorg/confluence:4.3.6-jdk7
      - ghcr.io/epicmorg/confluence:4.3.6-jdk7
