services:
  app:
    image: "epicmorg/zabbix-server-mysql:5.0"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-server-mysql:5.0
      - quay.io/epicmorg/zabbix-server-mysql:5.0
      - ghcr.io/epicmorg/zabbix-server-mysql:5.0
