# default JDK (Dockerfile) = jdk17; the extra JDK is built from Dockerfile.jdk11
services:
  app:
    image: "epicmorg/bitbucket:8.19.29"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/bitbucket:8.19.29
      - quay.io/epicmorg/bitbucket:8.19.29
      - ghcr.io/epicmorg/bitbucket:8.19.29
  app-jdk11:
    image: "epicmorg/bitbucket:8.19.29-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - docker.io/epicmorg/bitbucket:8.19.29-jdk11
      - quay.io/epicmorg/bitbucket:8.19.29-jdk11
      - ghcr.io/epicmorg/bitbucket:8.19.29-jdk11
  app-jdk17:
    image: "epicmorg/bitbucket:8.19.29-jdk17"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/bitbucket:8.19.29-jdk17
      - quay.io/epicmorg/bitbucket:8.19.29-jdk17
      - ghcr.io/epicmorg/bitbucket:8.19.29-jdk17
