services:
  app:
    image: "epicmorg/teamcity-server:2022.10.6"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/teamcity-server:2022.10.6
      - quay.io/epicmorg/teamcity-server:2022.10.6
      - ghcr.io/epicmorg/teamcity-server:2022.10.6
