services:
  app:
   image: "epicmorg/mattermost-enterprise-edition:11.10"
   build:
      context: .
   x-mirrors:
      - docker.io/epicmorg/mattermost-enterprise-edition:11.10
      - quay.io/epicmorg/mattermost-enterprise-edition:11.10
      - ghcr.io/epicmorg/mattermost-enterprise-edition:11.10
