services:
  app:
    image: "epicmorg/nextcloud:14"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - quay.io/epicmorg/nextcloud:14
      - ghcr.io/epicmorg/nextcloud:14
      - docker.io/epicmorg/nextcloud:14
