services:
  app:
    image: "epicmorg/teamcity-server:latest"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/teamcity-server:latest
      - ghcr.io/epicmorg/teamcity-server:latest
