services:
  app:
    image: "epicmorg/bitbucket-mesh:2.1.15"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket-mesh:2.1.15
      - docker.io/epicmorg/bitbucket-mesh:2.1.15-jdk11
      - quay.io/epicmorg/bitbucket-mesh:2.1.15
      - quay.io/epicmorg/bitbucket-mesh:2.1.15-jdk11
      - ghcr.io/epicmorg/bitbucket-mesh:2.1.15
      - ghcr.io/epicmorg/bitbucket-mesh:2.1.15-jdk11
