services:
  app:
    image: "epicmorg/crowd:0.4.3"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:0.4.3
      - docker.io/epicmorg/crowd:0.4.3-jdk6
      - quay.io/epicmorg/crowd:0.4.3
      - quay.io/epicmorg/crowd:0.4.3-jdk6
      - ghcr.io/epicmorg/crowd:0.4.3
      - ghcr.io/epicmorg/crowd:0.4.3-jdk6
