services:
  app:
    image: "epicmorg/nextcloud:20"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - quay.io/epicmorg/nextcloud:20
      - ghcr.io/epicmorg/nextcloud:20
      - docker.io/epicmorg/nextcloud:20