services:
  app:
    image: "epicmorg/bamboo:9.2.22"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bamboo:9.2.22
      - docker.io/epicmorg/bamboo:9.2.22-jdk11
      - quay.io/epicmorg/bamboo:9.2.22
      - quay.io/epicmorg/bamboo:9.2.22-jdk11
      - ghcr.io/epicmorg/bamboo:9.2.22
      - ghcr.io/epicmorg/bamboo:9.2.22-jdk11
