services:
  app:
    image: "epicmorg/testrail:auth-ad-5.2.1.3472"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:auth-ad-5.2.1.3472
      - ghcr.io/epicmorg/testrail:auth-ad-5.2.1.3472
      - docker.io/epicmorg/testrail:auth-ad-5.2.1.3472
