services:
  app:
    image: "epicmorg/crucible:1.6.5"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crucible:1.6.5
      - docker.io/epicmorg/crucible:1.6.5-jdk6
      - quay.io/epicmorg/crucible:1.6.5
      - quay.io/epicmorg/crucible:1.6.5-jdk6
      - ghcr.io/epicmorg/crucible:1.6.5
      - ghcr.io/epicmorg/crucible:1.6.5-jdk6
