services:
  app:
    image: "epicmorg/git:1.9"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/git:1.9
      - ghcr.io/epicmorg/git:1.9
      - docker.io/epicmorg/git:1.9
