services:
  app:
    image: "epicmorg/confluence:9.5.1"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:9.5.1
  app-jdk17:
    image: "epicmorg/confluence:9.5.1-jdk17"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:9.5.1-jdk17
  app-jdk21:
    image: "epicmorg/confluence:9.5.1-jdk21"
    build:
      context: .
      dockerfile: Dockerfile.jdk21
    x-mirrors:
      - quay.io/epicmorg/confluence:9.5.1-jdk21