services:
  app:
    image: "epicmorg/confluence:6.6.11"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:6.6.11
  app-jdk8:
    image: "epicmorg/confluence:6.6.11-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/confluence:6.6.11-jdk8
