services:
  app:
    image: "epicmorg/crowd:6.2.6"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/crowd:6.2.6
      - docker.io/epicmorg/crowd:6.2.6-jdk17
      - quay.io/epicmorg/crowd:6.2.6
      - quay.io/epicmorg/crowd:6.2.6-jdk17
      - ghcr.io/epicmorg/crowd:6.2.6
      - ghcr.io/epicmorg/crowd:6.2.6-jdk17
