services:
  app:
    image: "epicmorg/testrail:5.7.0.3951"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - quay.io/epicmorg/testrail:5.7.0.3951
      - ghcr.io/epicmorg/testrail:5.7.0.3951
      - docker.io/epicmorg/testrail:5.7.0.3951
