services:
  app:
    image: "epicmorg/fisheye-crucible:3.3.2"
    build:
      context: .
      dockerfile: Dockerfile.jdk7
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:3.3.2
  app-jdk6:
    image: "epicmorg/fisheye-crucible:3.3.2-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:3.3.2-jdk6
  app-jdk7:
    image: "epicmorg/fisheye-crucible:3.3.2-jdk7"
    build:
      context: .
      dockerfile: Dockerfile.jdk7
    x-mirrors:
      - quay.io/epicmorg/fisheye-crucible:3.3.2-jdk7
