services:
  app:
    image: "epicmorg/zabbix-snmptraps:7.2"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/zabbix-snmptraps:7.2
      - quay.io/epicmorg/zabbix-snmptraps:7.2
      - ghcr.io/epicmorg/zabbix-snmptraps:7.2
