services:
  app:
    image: "epicmorg/nextcloud:33"
    build:
      context: .
    x-squash: true
    x-mirrors:
      - quay.io/epicmorg/nextcloud:33
      - ghcr.io/epicmorg/nextcloud:33
      - docker.io/epicmorg/nextcloud:33
      - quay.io/epicmorg/nextcloud:latest
      - ghcr.io/epicmorg/nextcloud:latest
      - docker.io/epicmorg/nextcloud:latest
