services:
  app:
    image: "epicmorg/vscode-server:docker"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/vscode-server:docker
      - quay.io/epicmorg/vscode-server:docker
      - ghcr.io/epicmorg/vscode-server:docker
