services:
  app:
    image: "epicmorg/bitbucket:7.21.9"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:7.21.9
  app-jdk8:
    image: "epicmorg/bitbucket:7.21.9-jdk8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/bitbucket:7.21.9-jdk8
  app-jdk11:
    image: "epicmorg/bitbucket:7.21.9-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - quay.io/epicmorg/bitbucket:7.21.9-jdk11
