services:
  app:
    image: "epicmorg/bitbucket:7.6.3"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/bitbucket:7.6.3
      - quay.io/epicmorg/bitbucket:7.6.3
      - ghcr.io/epicmorg/bitbucket:7.6.3
  app-jdk8:
    image: "epicmorg/bitbucket:7.6.3-jdk8"
    build:
      context: .
    x-mirrors:
      - docker.io/epicmorg/bitbucket:7.6.3-jdk8
      - quay.io/epicmorg/bitbucket:7.6.3-jdk8
      - ghcr.io/epicmorg/bitbucket:7.6.3-jdk8
  app-jdk11:
    image: "epicmorg/bitbucket:7.6.3-jdk11"
    build:
      context: .
      dockerfile: Dockerfile.jdk11
    x-mirrors:
      - docker.io/epicmorg/bitbucket:7.6.3-jdk11
      - quay.io/epicmorg/bitbucket:7.6.3-jdk11
      - ghcr.io/epicmorg/bitbucket:7.6.3-jdk11
