services:
  app:
    image: "epicmorg/confluence:6.6.8"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/confluence:6.6.8
      - docker.io/epicmorg/confluence:6.6.8-jdk8
      - quay.io/epicmorg/confluence:6.6.8
      - quay.io/epicmorg/confluence:6.6.8-jdk8
      - ghcr.io/epicmorg/confluence:6.6.8
      - ghcr.io/epicmorg/confluence:6.6.8-jdk8
