services:
  app:
    image: "epicmorg/bitbucket:10.2.7"
    build:
      context: .
    x-squash: false
    x-mirrors:
      - docker.io/epicmorg/bitbucket:10.2.7
      - docker.io/epicmorg/bitbucket:10.2.7-jdk21
      - quay.io/epicmorg/bitbucket:10.2.7
      - quay.io/epicmorg/bitbucket:10.2.7-jdk21
      - ghcr.io/epicmorg/bitbucket:10.2.7
      - ghcr.io/epicmorg/bitbucket:10.2.7-jdk21
