services:
  app:
    image: "epicmorg/fisheye:1.3.8"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye:1.3.8
  app-jdk6:
    image: "epicmorg/fisheye:1.3.8-jdk6"
    build:
      context: .
    x-mirrors:
      - quay.io/epicmorg/fisheye:1.3.8-jdk6
